apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: transport-databases
type: Opaque
stringData:
  postgres-password: "kowihan123"
  postgres-gis-password: "transport_password123"
  mysql-password: "tickets_password123"
  mysql-root-password: "root123"
  mssql-password: "Kowihan!1234"
  mongodb-password: "kowihan123"
  redis-password: "redis123"
  rabbitmq-password: "password123456"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: transport-prod
type: Opaque
stringData:
  jwt-secret: "MaSuperCleSecretePourLeProjetTransportUrbainQuiEstTresLongueEtComplexe123"
  stripe-api-key: "sk_test_51SIrRuRxfAGItUbxU9eS5AMxaOM60muqMHCJ32d7IBYlwGEYD2DqNSw4hew3nRDY0QUhuM9pDOyXhEO2J5IMmVnI00Ybeo3SNB"
  stripe-webhook-secret: "whsec_qaRnUqiWgellHPCtuiQO7SEuZHtDVM8q"
  email-user: "d1416f55fc84d8"
  email-pass: "72019289c18555"
  twilio-account-sid: "ACee0037d40245135d2b7596f01b288261"
  twilio-auth-token: "7cb03af5c09ce1047f2f9537ffb9ecd9"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: transport-databases
data:
  postgres-db: "user_db"
  postgres-user: "kowihan"
  postgres-gis-db: "transport_db"
  postgres-gis-user: "transport_user"
  mysql-db: "tickets_db"
  mysql-user: "tickets_user"
  mongodb-db: "notifications_db"
  mongodb-user: "root"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: transport-prod
data:
  email-host: "sandbox.smtp.mailtrap.io"
  email-port: "587"
  twilio-phone: "+19785707940"
